name = "ScatteringOptics"
uuid = "e317c96f-4a6f-4ae9-8016-294fb9063ff5"
authors = ["Anna Tartaglia", "Kazunori Akiyama"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
